word_list = [
    "murcielago", "elefante", "montana", "computador", "aventura",
    "biblioteca", "chocolate", "helicoptero", "mariposa", "volcan",
    "paraguas", "camiseta", "carretera", "universo", "jirafa",
    "esmeralda", "piramide", "cuaderno", "sandwich", "pelicula",
    "dinosaurio", "laberinto", "tesoro", "ventana", "guitarra",
    "castillo", "oceano", "astronauta", "semaforo", "bicicleta",
    "pantalla", "ingeniero", "ambiente", "programacion", "teclado",
    "raton", "monitor", "celular", "auriculares", "microfono",
    "fotografia", "naturaleza", "tormenta", "relampago", "desierto",
    "glaciar", "bosque", "cascada", "serpiente", "rinoceronte",
    "hipopotamo", "ornitorrinco", "mapache", "armadillo", "colombia",
    "bogota", "medellin", "cartagena", "villavicencio", "sumapaz",
    "ingenieria", "algoritmo", "variable", "funciones", "condicional",
    "bucle", "diccionario", "matematicas", "geografia", "historia",
    "filosofia", "astronomia", "microscopio", "telescopio", "laboratorio",
    "electricidad", "reciclaje", "sostenibilidad", "ecosistema", "biodiversidad",
    "contaminacion", "hidrologia", "cartografia", "meteorologia", "vegetacion",
    "orquidea", "frailejon", "colibri", "cocodrilo", "chimpance",
    "muralla", "palacio", "catedral", "universidad", "restaurante",
    "aeropuerto", "ferrocarril", "motocicleta", "automovil", "camioneta",
    "destornillador", "martillo", "linterna", "mochila", "brujula",
    "supermercado", "panaderia", "cafeteria", "heladeria", "pescaderia"
]
